@echo off
echo [步骤1/5] 正在拉取最新仓库代码...
git pull origin main --force
echo [步骤2/5] 正在清理Hexo静态文件...
hexo clean
echo [步骤3/5] 正在生成Hexo静态文件...
hexo g
echo [步骤4/5] 正在部署到GitHub Pages...
hexo deploy
echo [步骤5/5] 部署成功！20秒后自动退出...
timeout /t 20 /nobreak >nul
exit