@echo off
# 自动拉取最新仓库，同时生成静态文件，并且部署静态到github
echo Running Git Pull...
git pull origin main --force
echo Cleaning Hexo...
hexo clean
echo Generating Hexo...
hexo g
echo Deploying Hexo...
hexo deploy
echo deploy success
timeout /t 3 /nobreak
pause